name: Build and Publish

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Deploy to Now
        uses: actions/zeit-now@1.0.0
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        with:
          args: --no-clipboard deploy > $HOME/${{ github.action }}.txt

      - name: Alias deployment
        uses: actions/zeit-now@1.0.0
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        with:
          args: alias `cat /github/home/deploy.txt` ${{ github.sha }}

      - name: Filter master branch
        uses: actions/bin/filter@master
        with:
          args: branch master

      - name: Run Jest
        uses: stefanoeb/jest-action@master

      - name: Release to production
        uses: actions/zeit-now@1.0.0
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        with:
          args: now --target production
